#\uD3EC\uD2B8 \uC124\uC815
Server:
    port: 6009
jwt:
    secret: asajksdfkjawkejb@nlkajsdl&*$&@G@KJHBFOASGKJHGBHJCD*&CT#SKJHBLSD*FYdkljfasdn@kjbasdfklxuerb
#저장 경로
file:
    dir: /home/t23209/educrat/public/assets/img/courses/
external:
    api:
        url: http://ceprj.gachon.ac.kr:60009/concentrate
openai:
    api-key: YOUR_OPENAI_API_KEY_HERE

spring:
    servlet:
        multipart:
            max-file-size: 1GB
            max-request-size: 1GB
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/db23209
        username: dbid232
        password: dbpass232
    jpa:
        properties:
            hibernate:
                #show_sql: true #SQL \uCFFC\uB9AC \uCD9C\uB825
                format_sql: true #SQL \uD3EC\uB9F7 \uD15C\uD50C\uB9BF
                show-sql : true

        hibernate:
            ddl-auto: update
        database-platform: org.hibernate.dialect.MariaDBDialect
    devtools:
        livereload:
            enabled: true
    thymeleaf:
        cache: false





